### ISSUE TITLE
Unable to detect your Java path error when creating new DAG account

### ISSUE THREAD

**Issue by maaatey** [grvlle/constellation_wallet#76]
Hi guys, when trying to create a new Molly desktop account with [Windows] Molly Wallet - 0.19 Beta I get this error "Unable to detect your Java path. Please make sure that Java has been installed."   
Any ideas how I get around this??

Thanks
John

**Comment by grvlle** [comment]
Hey John,

Thanks for using the Molly Wallet. This is most likely due to your JAVA installation not being in your PATH env variable. If running `where java` in cmd.exe doesn't return a java path, there is no way for the molly wallet to detect in either. See below instructions.

1. Download the latest version of the Molly Wallet:
https://github.com/grvlle/constellation_wallet/releases/
2. Download and install OpenJDK
https://www.oracle.com/java/technologies/javase-jdk14-downloads.html
3. If the wallet complains about not having Java installed despite having installed the version in step two. Follow this guide to set the JAVA_HOME enviornmental variable
https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html
4. Make sure that it's also included in your PATH variable:
https://www.java.com/en/download/help/path.xml

**Comment by maaatey** [comment]
Thanks so much Martin, I got it going!
